### PR TITLE
fix compilation errors and warnings on Ubuntu

### PR DESCRIPTION
**Pull request by Maxime2**

### CODE REVIEW

**Comment by SamuelMarks** [comment]
It's a good question, should one follow https://man.freebsd.org/cgi/man.cgi?query=asprintf&apropos=0&sektion=3&manpath=FreeBSD+6.2-RELEASE&format=html https://man.openbsd.org/OpenBSD-5.5/printf.3#HISTORY

Also if you look at alternate libc implementations like the popular musl, from their mailing-list: https://www.openwall.com/lists/musl/2012/12/28/1
```patch
-#ifdef _GNU_SOURCE
+#if defined _GNU_SOURCE || defined _BSD_SOURCE
```

Also there is the `__GNUC__` from glibc. Alternatively an explicit check in `CMakeLists.txt` of the [`CheckSymbolExists`](https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html) variety:
```cmake
check_symbol_exists(asprintf "stdio.h" HAVE_ASPRINTF)
```

PS: The solution I was using is in that `c89stringutils_string_extras` header: https://github.com/offscale/c89stringutils/blob/8d11ef4/c89stringutils/c89stringutils_string_extras.h#L87-L91

**Comment by SamuelMarks** [comment]
Good start! - I moved the guards to the wrong place when I was working on MSVC fixes.

With a serious cross-platform and cross-toolchain focus however, makes me want to point out the alternative locations for `asprintf` including:
  - https://man.freebsd.org/cgi/man.cgi?query=asprintf&apropos=0&sektion=3&manpath=FreeBSD+6.2-RELEASE&format=html
  - https://man.openbsd.org/OpenBSD-5.5/printf.3#HISTORY

Alternate libc implementations like the popular [musl](https://musl.libc.org), have included `asprintf` in both circumstances; from their mailing-list: https://www.openwall.com/lists/musl/2012/12/28/1
```patch
-#ifdef _GNU_SOURCE
+#if defined _GNU_SOURCE || defined _BSD_SOURCE
```

Also there is the `__GNUC__` from glibc. Alternatively an explicit check in `CMakeLists.txt` of the [`CheckSymbolExists`](https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html) variety:
```cmake
check_symbol_exists(asprintf "stdio.h" HAVE_ASPRINTF)
```

PS: The solution I was using is in that `c89stringutils_string_extras` header: https://github.com/offscale/c89stringutils/blob/8d11ef4/c89stringutils/c89stringutils_string_extras.h#L87-L91

**Comment by Maxime2** [comment]
The question is if `asprintf` presence is a requirement. If so, you need to break cmake run with a synopsis, otherwise you need a in-house `asprintf` implementation to be used then. Unfortunately, `check_symbol_exists` doesn't break cmake configuration if `asprintf` is not found.

**Comment by SamuelMarks** [comment]
Yes my https://github.com/offscale/c89stringutils provides `asprintf`. But yeah the `check_symbol_exists` is rough.

https://man7.org/linux/man-pages/man7/feature_test_macros.7.html

Is there a trick to checking if the toolchain supports `_GNU_SOURCE` or `_BSD_SOURCE`?

**Comment by SamuelMarks** [comment]
Yes my https://github.com/offscale/c89stringutils provides `asprintf`. But yeah the `check_symbol_exists` is rough.

https://man7.org/linux/man-pages/man7/feature_test_macros.7.html

Is there a trick to checking if the toolchain—libc in particular—supports `_GNU_SOURCE` or `_BSD_SOURCE`?

**Pull request closed without merging**
